from fastapi.testclient import TestClient
from PIL import Image
import io
import sys
import os

# Allow test runs without a token
os.environ.setdefault("ALLOW_NO_TOKEN", "true")

# Add parent directory to path to import app
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app import app

client = TestClient(app)

def create_dummy_image(width, height, format='JPEG'):
    img = Image.new('RGB', (width, height), color='red')
    img_byte_arr = io.BytesIO()
    img.save(img_byte_arr, format=format)
    img_byte_arr.seek(0)
    return img_byte_arr

def test_health_check():
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "healthy", "service": "model-service"}

def test_predict_high_quality():
    # Create large image (high quality)
    img_bytes = create_dummy_image(2000, 3000)
    files = {'file': ('test.jpg', img_bytes, 'image/jpeg')}
    
    response = client.post("/predict", files=files)
    assert response.status_code == 200
    data = response.json()
    
    assert data["quality"] == "high"
    assert data["score"] == 92
    assert "rich_text_report" in data
    assert "semantic_tags" in data
    assert "High Res" in data["semantic_tags"]

def test_predict_low_quality():
    # Create small image (low quality)
    img_bytes = create_dummy_image(100, 100)
    files = {'file': ('test.jpg', img_bytes, 'image/jpeg')}
    
    response = client.post("/predict", files=files)
    assert response.status_code == 200
    data = response.json()
    
    assert data["quality"] == "low"
    assert data["score"] == 55
    assert "Low Res" in data["semantic_tags"]

def test_invalid_file_type():
    files = {'file': ('test.txt', b'not an image', 'text/plain')}
    response = client.post("/predict", files=files)
    assert response.status_code == 400
    assert "File must be one of" in response.json()["detail"]

def test_predict_with_png():
    """Test that PNG images are accepted."""
    img_bytes = create_dummy_image(2000, 3000, format='PNG')
    files = {'file': ('test.png', img_bytes, 'image/png')}
    
    response = client.post("/predict", files=files)
    assert response.status_code == 200
    data = response.json()
    assert data["quality"] == "high"

def test_predict_response_structure():
    """Test that the response contains all expected fields."""
    img_bytes = create_dummy_image(2000, 3000)
    files = {'file': ('test.jpg', img_bytes, 'image/jpeg')}
    
    response = client.post("/predict", files=files)
    assert response.status_code == 200
    data = response.json()
    
    # Check all required fields exist
    assert "quality" in data
    assert "score" in data
    assert "defects" in data
    assert "reasons" in data
    assert "rich_text_report" in data
    assert "semantic_tags" in data
    assert "processed_at" in data
    
    # Check defects structure
    defects = data["defects"]
    assert "finger_in_frame" in defects
    assert "skew_degrees" in defects
    assert "blur" in defects
    assert "glare" in defects
    assert "cutoff_edges" in defects

def test_invalid_image_data():
    """Test handling of corrupt/invalid image data."""
    files = {'file': ('test.jpg', b'not valid image data', 'image/jpeg')}
    response = client.post("/predict", files=files)
    assert response.status_code == 400
    assert "Invalid image file" in response.json()["detail"]

def test_rich_text_report_format():
    """Test that the rich text report is properly formatted markdown."""
    img_bytes = create_dummy_image(2000, 3000)
    files = {'file': ('test.jpg', img_bytes, 'image/jpeg')}
    
    response = client.post("/predict", files=files)
    assert response.status_code == 200
    data = response.json()
    
    report = data["rich_text_report"]
    assert "## " in report  # Has markdown headers
    assert "AI Analysis" in report
    assert "Generated by AI Model Service" in report

def test_authentication_required():
    """Test that authentication is enforced when token is set."""
    # Save original env vars
    original_token = os.environ.get("MODEL_API_TOKEN")
    original_allow = os.environ.get("ALLOW_NO_TOKEN")
    
    try:
        # Set up token authentication
        os.environ["MODEL_API_TOKEN"] = "test-secret-token"
        os.environ["ALLOW_NO_TOKEN"] = "false"
        
        # Reimport app to pick up new env vars
        import importlib
        import app as app_module
        importlib.reload(app_module)
        test_client = TestClient(app_module.app)
        
        img_bytes = create_dummy_image(100, 100)
        files = {'file': ('test.jpg', img_bytes, 'image/jpeg')}
        
        # Request without token should fail
        response = test_client.post("/predict", files=files)
        assert response.status_code == 401
        
        # Request with wrong token should fail
        response = test_client.post("/predict", files=files, headers={"x-api-token": "wrong-token"})
        assert response.status_code == 401
        
        # Request with correct token should succeed
        response = test_client.post("/predict", files=files, headers={"x-api-token": "test-secret-token"})
        assert response.status_code == 200
        
    finally:
        # Restore original env vars
        if original_token:
            os.environ["MODEL_API_TOKEN"] = original_token
        else:
            os.environ.pop("MODEL_API_TOKEN", None)
        if original_allow:
            os.environ["ALLOW_NO_TOKEN"] = original_allow
        else:
            os.environ["ALLOW_NO_TOKEN"] = "true"
        # Reload app with original settings
        import importlib
        import app as app_module
        importlib.reload(app_module)


def test_content_type_mismatch_rejected():
    """Reject files where declared content-type and actual format differ."""
    img_bytes = create_dummy_image(2000, 2000, format='PNG')
    files = {'file': ('test.png', img_bytes, 'image/jpeg')}

    response = client.post("/predict", files=files)
    assert response.status_code == 400
    assert "content type" in response.json()["detail"].lower()


def test_rejects_file_over_max_upload_mb():
    """Reject uploads that exceed MAX_UPLOAD_MB."""
    original_max_upload = os.environ.get("MAX_UPLOAD_MB")

    try:
        os.environ["MAX_UPLOAD_MB"] = "0.001"  # ~1KB
        import importlib
        import app as app_module
        importlib.reload(app_module)
        test_client = TestClient(app_module.app)

        img_bytes = create_dummy_image(2000, 2000, format='PNG')
        files = {'file': ('big.png', img_bytes, 'image/png')}

        response = test_client.post("/predict", files=files)
        assert response.status_code == 413
    finally:
        if original_max_upload is not None:
            os.environ["MAX_UPLOAD_MB"] = original_max_upload
        else:
            os.environ.pop("MAX_UPLOAD_MB", None)
        import importlib
        import app as app_module
        importlib.reload(app_module)
        global client
        client = TestClient(app_module.app)


def test_internal_error_sanitized(monkeypatch):
    """Internal errors should not leak implementation details."""
    import importlib
    import app as app_module
    importlib.reload(app_module)
    test_client = TestClient(app_module.app)

    def boom(_):
        raise RuntimeError("simulated failure detail")

    monkeypatch.setattr(app_module, "dummy_quality_score", boom)

    img_bytes = create_dummy_image(2000, 3000)
    files = {'file': ('test.jpg', img_bytes, 'image/jpeg')}

    response = test_client.post("/predict", files=files)
    assert response.status_code == 500
    assert "internal processing error" in response.json()["detail"].lower()


def test_rejects_when_pixel_count_exceeds_limit():
    """Reject images that exceed configured pixel budget."""
    original_max_pixels = os.environ.get("MAX_PIXELS")
    try:
        os.environ["MAX_PIXELS"] = "10000"  # very small limit
        import importlib
        import app as app_module
        importlib.reload(app_module)
        local_client = TestClient(app_module.app)

        img_bytes = create_dummy_image(200, 200)  # 40k pixels
        files = {'file': ('test.jpg', img_bytes, 'image/jpeg')}

        response = local_client.post("/predict", files=files)
        assert response.status_code == 413
        assert "dimensions exceed" in response.json()["detail"].lower()
    finally:
        if original_max_pixels is not None:
            os.environ["MAX_PIXELS"] = original_max_pixels
        else:
            os.environ.pop("MAX_PIXELS", None)
        import importlib
        import app as app_module
        importlib.reload(app_module)
        global client
        client = TestClient(app_module.app)
